-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.netflix_titles
(
    show_id text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    director text COLLATE pg_catalog."default",
    "cast" text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    date_added text COLLATE pg_catalog."default",
    release_year integer NOT NULL,
    rating text COLLATE pg_catalog."default",
    duration text COLLATE pg_catalog."default" NOT NULL,
    listed_in text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL
);
END;